"""add: WorkoutRoutine and WorkoutRoutineRelationship

Revision ID: 17e7c598e1ab
Revises: 2a403bd280d9
Create Date: 2024-07-22 15:16:49.362515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17e7c598e1ab'
down_revision = '2a403bd280d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_routines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_workout_routines_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_routine_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=True),
    sa.Column('workout_routine_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], name=op.f('fk_workout_routine_relationships_workout_id_workouts')),
    sa.ForeignKeyConstraint(['workout_routine_id'], ['workout_routines.id'], name=op.f('fk_workout_routine_relationships_workout_routine_id_workout_routines')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_routine_relationships')
    op.drop_table('workout_routines')
    # ### end Alembic commands ###
