"""created user, workout and userWorkout tables

Revision ID: 34654d811dad
Revises: 
Create Date: 2024-06-26 09:55:39.618205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34654d811dad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('favorite_workout', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('force', sa.String(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('mechanic', sa.String(), nullable=True),
    sa.Column('equipment', sa.String(), nullable=True),
    sa.Column('primary_muscles', sa.String(), nullable=True),
    sa.Column('secondary_muscles', sa.String(), nullable=True),
    sa.Column('instructions', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.CheckConstraint("level IN ('beginner', 'intermediate', 'expert')", name='ck_workout_level'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('workout_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_workouts_user_id_users')),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], name=op.f('fk_user_workouts_workout_id_workouts')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_workouts')
    op.drop_table('workouts')
    op.drop_table('users')
    # ### end Alembic commands ###
