"""add: image_src for routines

Revision ID: b8350dfc6eea
Revises: f4e7b5acdb6a
Create Date: 2024-07-30 11:13:37.697819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8350dfc6eea'
down_revision = 'f4e7b5acdb6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_routines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_src', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_routines', schema=None) as batch_op:
        batch_op.drop_column('image_src')

    # ### end Alembic commands ###
